services:
  eme_front:
    image: alejoczombos/eme-front:latest
    ports:
      - "80:80"
    networks:
      - app-network

  eme_back:
    image: alejoczombos/eme-back:latest
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET: ${SECRET}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_ACCESS: ${S3_SECRET_ACCESS}
      RCIA_ADMIN_NAME: ${RCIA_ADMIN_NAME}
      RCIA_ADMIN_PASSWORD: ${RCIA_ADMIN_PASSWORD}
      CTES_ADMIN_NAME: ${CTES_ADMIN_NAME}
      CTES_ADMIN_PASSWORD: ${CTES_ADMIN_PASSWORD}
      RSP_ADMIN_NAME: ${RSP_ADMIN_NAME}
      RSP_ADMIN_PASSWORD: ${RSP_ADMIN_PASSWORD}
      SUPER_ADMIN_NAME: ${SUPER_ADMIN_NAME}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
    depends_on:
      - eme_db
    networks:
      - app-network

  eme_db:
    image: mysql:8.0
    container_name: eme_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
