services:
  app:
    container_name: eme_admin
    build: .
    env_file:
      - .env
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SECRET: ${SECRET}
    ports:
      - "8080:8080"
    restart: unless-stopped
