import os

DATABASE_NAME = os.getenv("DATABASE_NAME")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")

SECRET = os.getenv("SECRET")
RCIA_ADMIN_NAME = os.getenv("RCIA_ADMIN_NAME")
RCIA_ADMIN_PASSWORD = os.getenv("RCIA_ADMIN_PASSWORD")
CTES_ADMIN_NAME = os.getenv("CTES_ADMIN_NAME")
CTES_ADMIN_PASSWORD = os.getenv("CTES_ADMIN_PASSWORD")
RSP_ADMIN_NAME = os.getenv("RSP_ADMIN_NAME")
RSP_ADMIN_PASSWORD = os.getenv("RSP_ADMIN_PASSWORD")
SUPER_ADMIN_NAME = os.getenv("SUPER_ADMIN_NAME")
SUPER_ADMIN_PASSWORD = os.getenv("SUPER_ADMIN_PASSWORD")

S3_BUCKET = os.getenv("S3_BUCKET")
S3_REGION = os.getenv("S3_REGION")
S3_ACCESS_KEY = os.getenv("S3_ACCESS_KEY")
S3_SECRET_ACCESS = os.getenv("S3_SECRET_ACCESS")