import os


DATABASE_NAME = os.getenv("DATABASE_NAME")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")

ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD")
SECRET = os.getenv("SECRET")